### PR TITLE
Add fedmenu to github2fedmsg

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by pypingou** [comment]
Fair warning: un-tested :)

**Comment by ralphbean** [comment]
> Fair warning: un-tested :)

Could you not get it working?  https://github.com/fedora-infra/github2fedmsg#hacking

**Comment by pypingou** [comment]
Got it running on my old venv, seems to run fine although for some reason the logo seems a little distorted but no idea why, can't something in the css.

**Comment by ralphbean** [comment]
> logo seems a little distorted

Hm.  that must be fedmenu's fault.  We can sort that out later, no?  :+1: to merge!

**Comment by pypingou** [comment]
On Wed, Apr 29, 2015 at 05:04:32PM -0700, Ralph Bean wrote:

> ```
>  logo seems a little distorted
> ```
> 
>    Hm. that must be fedmenu's fault. We can sort that out later, no? 

I think so.

> :+1: to merge!

Thanks

**Pull request merged**
